### ISSUE TITLE
[Build issus] 编译失败

### ISSUE THREAD

**Issue by timfaner** [CAICT-DEV/BID-SDK-JAVA#1]
编译时遇到以下问题：
```
[ERROR] 不再支持源选项 6。请使用 7 或更高版本。
[ERROR] 不再支持目标选项 6。请使用 7 或更高版本。
[INFO] 2 errors
``` 

java版本：java 15.0.1 2020-10-20

请问怎样解决？
或者可以把编译好的jar包放在release中吗？

**Comment by caict-develop-zhangbo** [comment]
您好，
我们用java15进行了测试，没有遇到该问题，可能是您那里ide配置的问题，具体问题我们可以帮您一起看以下。
编译好的jar包是在BID-SDK项目 的src/target目录下的, 您看是否可以直接使用

**Comment by caict-develop-zhangbo** [comment]
> 编译时遇到以下问题：
> 
> ```
> [ERROR] 不再支持源选项 6。请使用 7 或更高版本。
> [ERROR] 不再支持目标选项 6。请使用 7 或更高版本。
> [INFO] 2 errors
> ```
> 
> java版本：java 15.0.1 2020-10-20
> 
> 请问怎样解决？
> 或者可以把编译好的jar包放在release中吗？

您好，
我们用java15进行了测试，没有遇到该问题，可能是您那里ide配置的问题，具体问题我们可以帮您一起看一下。
编译好的jar包是在BID-SDK项目 的src/target目录下的, 您看是否可以直接使用
